### PR TITLE
parameter expansion examples

### PR DESCRIPTION
**Pull request by paxperscientiam**
This isn't complete. Just wanted to get my foot in the door. Nice work btw.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Cheers :+1:

**Comment by paxperscientiam** [comment]
@dylanaraps OK, I added two more assertions and their respective examples. What do you think?

**Comment by dylanaraps** [comment]
I don't think tests are needed here since these aren't functions.

**Comment by paxperscientiam** [comment]
@dylanaraps , I think I made a lot of mistakes. Gonna rethink things.

**Comment by dylanaraps** [comment]
All good, if you need any help or have any questions, feel free to message me :)

**Pull request closed without merging**
